### ISSUE TITLE
Stage the data from source systems as raw documents in MarkLogic database

### ISSUE THREAD

**Issue by HemantPuranik** [marklogic/data-hub-in-a-box#1]
This is Not a major gap. For initial scope, leverage mlcp or info studio. 
In future, orchestrate 'Initial Load' by leveraging ML9 - Data Movement SDK

**Comment by damonfeldman** [comment]
Short design note: the idea is that mlcp will call a specific DHIB transform-module and specify the name of the flow to use as a transform-param. This "transform" module will apply all plugins for the desired flow (the last of which is likely a persister plugin). 

In this way, we can leverage mlcp to run flows for ingest.
