### ISSUE TITLE
Update QuickStart to use Scaffolding class from data-hub jar

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/data-hub-in-a-box#38]
The Scaffolding class in data-hub creates the flow dir tree along with sample plugin files.

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

Let me work on this today. I'll push the code in the same latest PR later.

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

I have made changes to this. I just noticed that there are no distinctions in the folders and files created for input and conform flow. Let me know what are the required folder and files for each type of flows so I can make the adjustment. Thanks!
