### ISSUE TITLE
Domains should be called Entities

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/data-hub-in-a-box#53]
Rename Domains to Entities where applicable.

Entities will eventually align to entity services in ML 9.

subfolders for entities:

- flows
- schemas (TBD don't add for now)
- search options nodes (TBD don't add for now)
- rest options (TBD don't add for now)

**Comment by maeisabelle** [comment]
Hi @paxtonhare,

I'll be working on this ticket to help @gmarintes. Given such, I'll be making a lot of changes on both data-hub and quick-start as I'll be renaming all "Domain" to "Entity". I'll be using a new branch. Let me know Glenn if you have issues and comments on how to make the merging easier once I'm done with the changes.
