### ISSUE TITLE
Update dir tree to reflect where REST stuff lives

### ISSUE THREAD

**Issue by paxtonhare** [marklogic/data-hub-in-a-box#73]
Rest stuff (options, transforms, extensions) need live at the entity level.

This ticket is to  update the wiki to reflect the new home of said stuff.

**Comment by damonfeldman** [comment]
updated

**Comment by paxtonhare** [comment]
I'm guessing you missed my IM about this.

Needs to be :

/domains
  /name
    /input
      /REST
        ...
    /conformance
      /REST
        ...
